### ISSUE TITLE
Categorize shards

### ISSUE THREAD

**Issue by edwardloveall** [jdbann/crystal-toolbox#4]
Probably use this repo as a start: https://github.com/veelenga/awesome-crystal

**Comment by jdbann** [comment]
Breaking the ticket down a bit, there seems to be two decisions:

- Individual categories or multiple tags?
- Assigned by anonymous users or selected curators?

I think I'd prefer categories over tags. Discrete options ensure a category includes the right shards, even if it's not the ideal category—otherwise we could end up with different tags for a similar category.

As for anonymous users or curators, it depends on how much time we want to spend moderating!

**Comment by edwardloveall** [comment]
Eventually, I'd love to have something like "Sign in with Github" or whatever so they aren't anonymous. I think we could do anonymous for now though and not worry too much about auth.

Categories are good, yeah. I think this would be a good list to start with: https://github.com/veelenga/awesome-crystal

**Comment by jdbann** [comment]
I'm thinking for the first step:

- [ ] Create category model
- [ ] Lucky task to generate the list of categories
- [ ] Add category select field to shard submission form

Allow submitter to choose the shard's category and we can step in if necessary.

**Comment by edwardloveall** [comment]
Yeah sounds good to me!
